
from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

HEADER_FILL = PatternFill("solid", fgColor="17324D")
SECTION_FILL = PatternFill("solid", fgColor="0F8B8D")
LIGHT_FILL = PatternFill("solid", fgColor="EAF2F8")
GREEN_FILL = PatternFill("solid", fgColor="DDF3E4")
WHITE_FONT = Font(color="FFFFFF", bold=True)
THIN = Side(style="thin", color="C7D4DE")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
MONEY = '৳#,##0.00;[Red]-৳#,##0.00'


def add_metadata(
    wb: Workbook,
    *,
    bot_name: str,
    bot_version: str,
    month: str,
    generated_by: str,
    total_records: int,
) -> None:
    ws = wb.create_sheet("Metadata", 0)
    rows = [
        ("Bot Name", bot_name),
        ("Bot Version", bot_version),
        ("Company", "BURAQ"),
        ("Export Type", "Central Export"),
        ("Schema Version", "1.0"),
        ("Export Month", month),
        ("Generated At", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated By", generated_by),
        ("Total Records", total_records),
    ]
    ws.append(["Field", "Value"])
    for row in rows:
        ws.append(row)
    style_table(ws)


def style_table(ws, money_columns: tuple[str, ...] = ()) -> None:
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "A2"

    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = WHITE_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = BORDER

    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.border = BORDER
            cell.alignment = Alignment(vertical="center")

    for col in money_columns:
        for cell in ws[col][1:]:
            cell.number_format = MONEY

    for column in ws.columns:
        letter = get_column_letter(column[0].column)
        width = max((len(str(c.value or "")) for c in column), default=10) + 3
        ws.column_dimensions[letter].width = min(max(width, 12), 42)

    if ws.max_row >= 1 and ws.max_column >= 1:
        ws.auto_filter.ref = ws.dimensions


def append_summary(ws, rows: list[tuple[str, Any, str]]) -> None:
    ws.append(["Metric", "Value", "Meaning"])
    for metric, value, meaning in rows:
        ws.append([metric, value, meaning])

    style_table(ws)

    for row_no in range(2, ws.max_row + 1):
        metric = str(ws.cell(row_no, 1).value or "")
        if any(
            word in metric
            for word in (
                "Amount",
                "Expense",
                "Payment",
                "Balance",
                "Total",
            )
        ):
            if isinstance(ws.cell(row_no, 2).value, (int, float)):
                ws.cell(row_no, 2).number_format = MONEY


def _normalize_date(value: Any) -> tuple[str, str]:
    """
    Returns (YYYY-MM-DD, YYYY-MM).
    Supports datetime/date and common string formats.
    """
    if value is None:
        return "", ""

    if isinstance(value, datetime):
        dt = value
        return dt.strftime("%Y-%m-%d"), dt.strftime("%Y-%m")

    if isinstance(value, date):
        return value.strftime("%Y-%m-%d"), value.strftime("%Y-%m")

    text = str(value).strip()
    if not text:
        return "", ""

    # Remove a possible time part.
    date_part = text.split("T", 1)[0].split(" ", 1)[0]

    formats = (
        "%Y-%m-%d",
        "%Y/%m/%d",
        "%d/%m/%Y",
        "%d-%m-%Y",
        "%m/%d/%Y",
    )
    for fmt in formats:
        try:
            dt = datetime.strptime(date_part, fmt)
            return dt.strftime("%Y-%m-%d"), dt.strftime("%Y-%m")
        except ValueError:
            continue

    # Last safe fallback for a YYYY-MM prefix.
    if len(text) >= 7 and text[4] in "-/":
        month = text[:7].replace("/", "-")
        return text, month

    return text, ""


def _row_value(row: dict[str, Any], *names: str) -> Any:
    normalized = {
        str(key or "").strip().casefold().replace("_", " "): value
        for key, value in row.items()
    }
    for name in names:
        key = name.strip().casefold().replace("_", " ")
        if key in normalized:
            return normalized[key]
    return None


def build_expense_central_export(
    store,
    output: Path,
    month: str,
    generated_by: str = "Admin",
) -> Path:
    selected_rows: list[dict[str, Any]] = []

    for raw in store.get_all():
        row = dict(raw)
        raw_date = _row_value(row, "date", "expense date", "entry date")
        normalized_date, month_key = _normalize_date(raw_date)

        if month_key != month:
            continue

        category = str(
            _row_value(row, "category", "expense category", "type") or "Other"
        ).strip() or "Other"

        description = str(
            _row_value(row, "description", "details", "remarks", "note") or ""
        ).strip()

        amount_raw = _row_value(row, "amount", "expense amount", "total")
        try:
            amount = float(str(amount_raw or 0).replace(",", "").replace("৳", "").strip())
        except ValueError:
            amount = 0.0

        selected_rows.append(
            {
                "Date": normalized_date or str(raw_date or ""),
                "Category": category,
                "Description": description,
                "Amount": amount,
            }
        )

    total = sum(row["Amount"] for row in selected_rows)
    categories: dict[str, float] = {}
    daily: dict[str, float] = {}

    for row in selected_rows:
        category = row["Category"]
        amount = row["Amount"]
        categories[category] = categories.get(category, 0.0) + amount
        day = row["Date"]
        daily[day] = daily.get(day, 0.0) + amount

    wb = Workbook()
    wb.remove(wb.active)

    add_metadata(
        wb,
        bot_name="BusinessExpenseBot",
        bot_version="6.1",
        month=month,
        generated_by=generated_by,
        total_records=len(selected_rows),
    )

    summary_ws = wb.create_sheet("Summary")
    top_category = max(categories.items(), key=lambda item: item[1], default=("", 0.0))
    append_summary(
        summary_ws,
        [
            ("Month", month, "Selected accounting month"),
            ("Total Expense", total, "All monthly expenses"),
            ("Transaction Count", len(selected_rows), "Expense entries"),
            ("Top Category", top_category[0], "Highest expense category"),
            ("Top Category Amount", top_category[1], "Highest category total"),
        ],
    )

    transaction_ws = wb.create_sheet("Transactions")
    transaction_ws.append(["Date", "Category", "Description", "Amount"])
    for row in selected_rows:
        transaction_ws.append(
            [
                row["Date"],
                row["Category"],
                row["Description"],
                row["Amount"],
            ]
        )
    style_table(transaction_ws, money_columns=("D",))

    category_ws = wb.create_sheet("Category Summary")
    category_ws.append(["Month", "Category", "Transaction Count", "Amount"])
    for category, amount in sorted(
        categories.items(),
        key=lambda item: (-item[1], item[0].casefold()),
    ):
        count = sum(1 for row in selected_rows if row["Category"] == category)
        category_ws.append([month, category, count, amount])
    style_table(category_ws, money_columns=("D",))

    daily_ws = wb.create_sheet("Daily Summary")
    daily_ws.append(["Date", "Transaction Count", "Amount"])
    for day, amount in sorted(daily.items()):
        count = sum(1 for row in selected_rows if row["Date"] == day)
        daily_ws.append([day, count, amount])
    style_table(daily_ws, money_columns=("C",))

    wb.save(output)
    return output
